const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{

 const browser=await chromium.launch({headless:true,executablePath:process.env.KAIJU_QA_BROWSER||chromium.executablePath(),args:["--no-sandbox","--no-zygote","--disable-gpu","--disable-software-rasterizer","--use-gl=disabled"]});
 const page=await browser.newPage({viewport:{width:1360,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const checks=[];const check=(name,fn)=>{assert.ok(fn,name);checks.push(name)};
 await page.goto('file://'+path.resolve('preview/Modulo_Kaiju_Previa.html'));
 await page.waitForSelector('.kaiju-channel');await page.waitForTimeout(450);
 check('Três eixos no vínculo',await page.locator('.kaiju-channel').count()===3);
 check('Bloco do print e SVGs em loop removidos',await page.locator('[data-kj-kaiju-radar], [data-kj-summary-metric], animate, animateTransform').count()===0);
 check('Animação decorativa visível dentro do orçamento de dezoito loops',await page.evaluate(()=>{const n=document.getAnimations().filter(a=>a.playState==='running' && a.effect.getTiming().iterations===Infinity).length;return n>=3 && n<=18}));
 await page.waitForTimeout(450);await page.screenshot({path:'qa/Kaiju_Motion_Ampla.png'});
 await page.getByRole('button',{name:'Ajustar Sincronia',exact:true}).click();
 check('Atalho focou o canal correto',await page.locator('[data-percent="comunhao"]').evaluate(e=>document.activeElement===e));
 await page.locator('[data-percent="comunhao"]').fill('100');
 check('Estágio VI atualizado',await page.locator('[data-axis="comunhao"] [data-stage-label]').textContent()==='Equilíbrio Perfeito');
 check('Rascunho sinalizado no portador',await page.locator('[data-record="k03-mika"] .kaiju-draft-marker').isVisible());
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();
 check('Rascunho preservado entre abas',await page.locator('[data-kaiju-meter="comunhao"] [data-kaiju-percent]').textContent()==='100');
 await page.locator('[data-record="k03-ren"]').click();await page.locator('[data-record="k03-mika"]').click();
 check('Rascunho preservado entre portadores',await page.locator('[data-kaiju-meter="comunhao"] [data-kaiju-percent]').textContent()==='100');
 await page.getByRole('button',{name:'Salvar vínculo',exact:true}).click();
 check('Salvamento confirmado',await page.locator('[data-status]').textContent()==='Vínculo salvo');
 check('Rascunho limpo após salvar',await page.locator('[data-record="k03-mika"] .kaiju-draft-marker').isHidden());
 await page.getByRole('tab',{name:'Registro',exact:true}).click();
 await page.locator('[data-field="notes"]').fill('Notas revisadas');await page.getByRole('button',{name:'Descartar',exact:true}).click();
 check('Descarte restaurou notas',await page.locator('[data-field="notes"]').inputValue()!=='Notas revisadas');
 await page.getByRole('tab',{name:'Estágios',exact:true}).click();
 check('Mapa completo com 18 estágios',await page.locator('.kaiju-stage-column li').count()===18);
 await page.waitForTimeout(450);await page.screenshot({path:'qa/Kaiju_Motion_Estagios.png'});
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();
 await page.locator('[data-search]').fill('impossivel');check('Busca vazia visível',await page.locator('.kaiju-no-results').isVisible());await page.locator('[data-search]').fill('');
 await page.getByRole('button',{name:'Novo portador',exact:true}).click();check('Diálogo com foco inicial',await page.locator('.kaiju-create-form input').evaluate(e=>document.activeElement===e));
 await page.keyboard.press('Shift+Tab');check('Foco contido no diálogo',await page.locator('.kaiju-create-form button[type="submit"]').evaluate(e=>document.activeElement===e));
 await page.keyboard.press('Escape');check('Escape cancela e devolve foco',await page.locator('[data-command="new"]:visible').evaluate(e=>document.activeElement===e));
 await page.getByRole('button',{name:'Novo portador',exact:true}).click();await page.locator('.kaiju-create-form input').fill('Portador de teste');await page.getByRole('button',{name:'Criar vínculo',exact:true}).click();
 check('Novo portador criado',await page.locator('.kaiju-record-header h1').textContent()==='Portador de teste');
 await page.selectOption('#preview-role','player');
 check('Jogador sem edição/criação ou dados restritos',await page.locator('[data-tab="edit"],[data-command="new"], [data-command="save"]').count()===0 && await page.locator('[data-record="k03-ren"]').count()===0);
 await page.selectOption('#preview-role','gm');await page.selectOption('#preview-size','compact');await page.waitForTimeout(400);
 check('Navegação compacta disponível',await page.locator('[data-record-select]').isVisible());
 await page.selectOption('[data-record-select]','k03-mika');
 await page.waitForTimeout(450);await page.screenshot({path:'qa/Kaiju_Motion_Compacta.png'});
 await page.getByRole('tab',{name:'Estágios',exact:true}).click();
 await page.locator('.kaiju-body').evaluate(e=>e.scrollTop=260);
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();await page.getByRole('tab',{name:'Estágios',exact:true}).click();
 check('Rolagem preservada por seção',await page.locator('.kaiju-body').evaluate(e=>Math.abs(e.scrollTop-260)<2));
 await page.selectOption('#preview-motion','off');await page.getByRole('tab',{name:'Vínculo',exact:true}).click();
 check('Motion desligado não cria animações',await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length)===0);
 await page.selectOption('#preview-motion','auto');await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('tab',{name:'Estágios',exact:true}).click();
 check('Preferência do sistema reduz motion',await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length)===0);
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();
 await page.selectOption('#preview-size','desktop');
 await page.getByRole('button',{name:'Restaurar exemplos',exact:true}).click();
 check('Exemplos restaurados',await page.locator('[data-kaiju-meter="comunhao"] [data-kaiju-percent]').textContent()==='62');
 for(const width of [360,430,720,850,1180]){
  await page.setViewportSize({width,height:820});await page.waitForTimeout(400);
  const overflow=await page.locator('.kaiju-app,.kaiju-main,.kaiju-body').evaluateAll(es=>es.map(e=>({cls:e.className,extra:e.scrollWidth-e.clientWidth})).filter(x=>x.extra>2));
  check(`Sem overflow horizontal em ${width}px`,overflow.length===0);
  await page.getByRole('tab',{name:'Controles',exact:true}).click();
  const visible=await page.locator('.kaiju-body').evaluate(e=>e.scrollWidth<=e.clientWidth+2);check(`Controles acessíveis em ${width}px`,visible);
  await page.getByRole('tab',{name:'Vínculo',exact:true}).click();
 }
 await page.setViewportSize({width:1360,height:1000});await page.waitForTimeout(450);await page.waitForTimeout(450);await page.screenshot({path:'qa/Kaiju_Motion_Ampla.png'});
 for(let i=0;i<12;i++){await page.getByRole('tab',{name:i%2?'Vínculo':'Estágios',exact:true}).click()}
 await page.waitForTimeout(500);
 check('Trocas rápidas sem acúmulo de animações',await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length)<=18);
 await page.getByRole('tab',{name:'Vínculo',exact:true}).focus();await page.keyboard.press('End');
 check('Teclado End abre última aba',await page.getByRole('tab',{name:'Controles',exact:true}).getAttribute('aria-selected')==='true');
 await page.keyboard.press('Home');check('Teclado Home retorna ao vínculo',await page.getByRole('tab',{name:'Vínculo',exact:true}).getAttribute('aria-selected')==='true');
 await page.selectOption('#preview-size','compact');await page.getByRole('button',{name:'Novo portador',exact:true}).click();await page.keyboard.press('Escape');
 check('Diálogo compacto devolve foco ao botão visível',await page.locator('[data-command="new"]:visible').evaluate(e=>document.activeElement===e));
 await page.selectOption('#preview-size','desktop');
 await page.selectOption('#preview-motion','calm');await page.getByRole('tab',{name:'Estágios',exact:true}).click();
 check('Modo só navegação mantém as transições',await page.evaluate(()=>document.getAnimations().some(a=>a.playState==='running' && a.effect.getTiming().iterations!==Infinity)));
 await page.waitForTimeout(450);check('Modo só navegação termina em repouso',await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length)===0);
 await page.selectOption('#preview-motion','auto');await page.getByRole('tab',{name:'Vínculo',exact:true}).click();await page.waitForTimeout(500);
 await page.selectOption('#preview-size','compact');await page.locator('.kaiju-body').evaluate(e=>e.scrollTop=e.scrollHeight);await page.waitForTimeout(150);
 check('Canal fora da área visível pausa os três instrumentos',await page.locator('.kaiju-channel').first().evaluate(e=>!e.classList.contains('is-ambient-active') && e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length===0));
 await page.getByRole('button',{name:'Novo portador',exact:true}).click();await page.waitForTimeout(400);
 check('Abrir diálogo pausa as animações decorativas',await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running' && a.effect.getTiming().iterations===Infinity).length)===0);
 await page.keyboard.press('Escape');await page.waitForTimeout(150);
 check('Fechar diálogo retoma os instrumentos visíveis',await page.evaluate(()=>document.getAnimations().some(a=>a.playState==='running' && a.effect.getTiming().iterations===Infinity)));
 await page.selectOption('#preview-size','desktop');await page.locator('.kaiju-body').evaluate(e=>e.scrollTop=0);
 await page.waitForTimeout(400);
 check('Moldura do ícone usa duas camadas, incluindo contorno diagonal',await page.locator('.kaiju-channel-icon .kaiju-icon-core').count()===3);
 check('Barras têm degradê e brilho contido na região preenchida',await page.locator('[data-meter-fill]').evaluateAll(es=>es.every(e=>getComputedStyle(e).backgroundImage.includes('linear-gradient'))) && await page.locator('.kaiju-meter-route').count()===3);
 await page.waitForTimeout(450);await page.screenshot({path:'qa/Kaiju_HUD_v5_Ampla.png'});
 await page.selectOption('#preview-size','compact');await page.waitForTimeout(450);await page.screenshot({path:'qa/Kaiju_HUD_v5_Compacta.png'});
 await page.selectOption('#preview-size','desktop');await page.getByRole('tab',{name:'Estágios',exact:true}).click();await page.waitForTimeout(450);await page.screenshot({path:'qa/Kaiju_HUD_v5_Estagios.png'});
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();await page.waitForTimeout(500);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});
 check('Evento de página oculta interrompe as animações',await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length)===0);
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))});await page.waitForTimeout(100);
 check('Retorno à página restaura a ambientação',await page.evaluate(()=>document.getAnimations().some(a=>a.playState==='running' && a.effect.getTiming().iterations===Infinity)));
 await page.getByRole('tab',{name:'Controles',exact:true}).click();
 const colorBefore=await page.locator('[data-axis="vontade"]').evaluate(e=>getComputedStyle(e).getPropertyValue('--axis-color'));
 await page.locator('[data-percent="vontade"]').fill('100');
 const colorAfter=await page.locator('[data-axis="vontade"]').evaluate(e=>getComputedStyle(e).getPropertyValue('--axis-color'));
 check('A porcentagem altera o tom dentro da família do eixo',colorBefore!==colorAfter);
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();
 check('A leitura usa a mesma cor do controle',await page.locator('[data-kaiju-meter="vontade"]').evaluate(e=>getComputedStyle(e).getPropertyValue('--axis-color'))===colorAfter);
 await page.getByRole('button',{name:'Descartar',exact:true}).click();
 check('O preenchimento parcial exibe o degradê próprio da porcentagem',await page.locator('[data-kaiju-meter="vontade"] [data-meter-fill]').evaluate(e=>e.style.width==='48%' && getComputedStyle(e).backgroundSize==='100% 100%' && e.closest('.kaiju-channel').style.getPropertyValue('--axis-gradient').includes('linear-gradient')));
 check('O retrato não tem texto, grade ou retícula sobre o rosto',await page.locator('.kaiju-photo').evaluate(e=>e.querySelectorAll('.kaiju-scanner-label,.kaiju-photo-grid,.kaiju-photo-reticle,.kaiju-photo-caption,.kaiju-photo-top,.kaiju-scan-note').length===0 && !e.querySelector('.kaiju-scanner').textContent.trim()));
 check('Nome e designação ficam abaixo da imagem',await page.locator('.kaiju-portrait').evaluate(e=>e.querySelector('.kaiju-photo-caption').getBoundingClientRect().top>=e.querySelector('.kaiju-photo').getBoundingClientRect().bottom-1));
 check('O retrato de demonstração carrega offline',await page.locator('[data-portrait-image]').evaluate(e=>e.complete && e.naturalWidth>0));
 check('Scanner composto por seis instrumentos animados',await page.locator('.kaiju-scanner').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.effect.getTiming().iterations===Infinity).length===6));
 await page.waitForFunction(()=>document.querySelector('.kaiju-scan-pass')?.getAnimations().some(a=>a.playState==='running'));
 const scanBefore=await page.locator('.kaiju-scan-pass').evaluate(e=>{const a=e.getAnimations()[0];a.currentTime=Number(a.effect.getTiming().duration)*.1;return getComputedStyle(e).transform});
 await page.waitForTimeout(150);
 check('O feixe com rastro e malha percorre o retrato',await page.locator('.kaiju-scan-pass').evaluate(e=>getComputedStyle(e).transform)!==scanBefore && await page.locator('.kaiju-scan-mesh,.kaiju-scan-beam,.kaiju-scan-tip').count()===4);
 check('A varredura percorre a base e sai completamente da fotografia',await page.locator('.kaiju-scan-pass').evaluate(e=>{
   const a=e.getAnimations()[0];a.pause();const duration=Number(a.effect.getTiming().duration),photo=e.closest('.kaiju-photo'),h=photo.clientHeight;
   a.currentTime=duration*(.05+.67*(h-3)/(h+70));
   const beam=e.querySelector('.kaiju-scan-beam');const reaches=Math.abs(beam.getBoundingClientRect().bottom-(photo.getBoundingClientRect().bottom-4))<3;
   a.currentTime=duration*.74;const clears=e.getBoundingClientRect().top>=photo.getBoundingClientRect().bottom-2 && Number(getComputedStyle(e).opacity)===0;
   a.play();return reaches && clears;
 }));
 check('A confirmação completa sua expansão depois da passagem',await page.locator('.kaiju-scan-confirm').evaluate(e=>{
   const a=e.getAnimations()[0];a.pause();a.currentTime=Number(a.effect.getTiming().duration)*.84;
   const complete=getComputedStyle(e).transform==='matrix(1, 0, 0, 1, 0, 0)' && Number(getComputedStyle(e).opacity)>.9;a.play();return complete;
 }));
 check('O brilho percorre toda a região preenchida',await page.locator('.kaiju-meter-current').first().evaluate(e=>{
   const animation=e.getAnimations()[0];animation.pause();const timing=animation.effect.getTiming();animation.currentTime=Number(timing.duration)*.85;
   const route=e.closest('.kaiju-meter-route');const reaches=e.getBoundingClientRect().left>=route.getBoundingClientRect().right-2;
   animation.play();return reaches;
 }));

 await page.getByRole('tab',{name:'Registro',exact:true}).click();
 await page.locator('[data-portrait-upload]').setInputFiles({name:'retrato.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aM7sAAAAASUVORK5CYII=','base64')});
 await page.waitForTimeout(120);
 check('Imagem local pode ser escolhida para a demonstração',(await page.locator('[data-field="portrait"]').inputValue()).startsWith('data:image/png;base64,'));
 await page.getByRole('button',{name:'Salvar vínculo',exact:true}).click();
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();
 check('O retrato salvo aparece no dossiê',await page.locator('[data-portrait-image]').getAttribute('src').then(s=>s.startsWith('data:image/png;base64,')));
 await page.reload();await page.waitForSelector('.kaiju-photo');
 check('O retrato escolhido persiste ao reabrir a prévia',await page.locator('[data-portrait-image]').getAttribute('src').then(s=>s.startsWith('data:image/png;base64,')));
 await page.getByRole('tab',{name:'Registro',exact:true}).click();
 await page.locator('[data-field="portrait"]').fill('missing-portrait.png');
 await page.getByRole('tab',{name:'Vínculo',exact:true}).click();await page.waitForTimeout(150);
 check('Imagem indisponível mostra identificação alternativa',await page.locator('.kaiju-photo').evaluate(e=>e.classList.contains('image-unavailable')));
 await page.getByRole('button',{name:'Restaurar exemplos',exact:true}).click();await page.waitForTimeout(450);
 await page.waitForTimeout(100);
 check('A abertura das barras termina sem cobrir o degradê',await page.locator('.kaiju-meter-reveal').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().left>=e.parentElement.getBoundingClientRect().right-1)));
 check('O retrato permanece estático e sem filtros',await page.locator('[data-portrait-image]').evaluate(e=>getComputedStyle(e).transform==='none' && getComputedStyle(e).filter==='none' && e.getAnimations().length===0));
 await page.screenshot({path:'qa/Kaiju_HUD_v5_Ampla.png'});
 check('Sem exceções no navegador',errors.length===0);
 fs.writeFileSync('qa/ui-results.json',JSON.stringify({checks,errors,total:checks.length},null,2));
 console.log(JSON.stringify({total:checks.length,errors,screenshots:3}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
